### PR TITLE
table styles not scoped by .docson

### PR DESCRIPTION
**Pull request by bolshakov**

### CODE REVIEW

**Comment by lbovet** [comment]
Hi. Did you mean to make the PR onto my repository? The PR is onto your own master....

**Comment by bolshakov** [comment]
Hi, yep I mean your repo. No idea how this happened

**Comment by lbovet** [comment]
I merged it into my repo. You can close this one. Thanks

**Comment by bolshakov** [comment]
Thank you. I like docson so much!

**Pull request closed without merging**
